business_management/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
// use App\Http\Controllers\Admin\HomeController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes(['register'=>false]);

Route::prefix('admin')->group(function () {
    Route::get('/','Admin\HomeController@index')
    ->name('admin.index')
    ->middleware('auth');

    Route::resource('companie','Admin\CompanieController')->middleware('auth');
    Route::resource('employee','Admin\EmployeeController')->middleware('auth');
});

business_management/app/Companie.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Companie extends Model
{
    protected $guarded = [];

    public function employees(){
        return $this->hasMany('App\Employee');
    }
}

business_management/app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $guarded = [];

    public function companie(){
        return $this->belongsTo('App\Companie');
    }
}

business_management/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

business_management/app/Http/Controllers/Admin/CompanieController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Companie;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\CreateCompanieRequest;
use App\Http\Requests\EditCompanieRequest;
use App\Mail\MessageReceived;
use Illuminate\Support\Facades\Mail;

class CompanieController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin/record_companie',[
            'companies'=>Companie::first()->paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin/companie');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCompanieRequest $request)
    {
        $logo = $request->file('logo');
        $data = $request->validated();
        $data['logo'] =  $request->file('logo')->store('images');
        $data['name_logo'] =  $logo->getClientOriginalName();
        Companie::create($data);
        Mail::to(request('email'))->queue(new MessageReceived($data));
        return redirect()->route('companie.create')->with('status',__('successful company registration'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Companie  $companie
     * @return \Illuminate\Http\Response
     */
    public function show(Companie $companie)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Companie  $companie
     * @return \Illuminate\Http\Response
     */
    public function edit(Companie $companie)
    {
        return view('admin/edit_companie',[
            'companie'=>$companie
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Companie  $companie
     * @return \Illuminate\Http\Response
     */
    public function update(EditCompanieRequest $request, Companie $companie)
    {
        $data = $request->validated();
        if(request('logo')){
            $logo = $request->file('logo');
            $data['logo'] = $request->file('logo')->store('images');
            $data['name_logo'] = $logo->getClientOriginalName();
        }
        $companie->update($data);
        return redirect()->route('companie.index')->with('status',__('successfully upgraded company'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Companie  $companie
     * @return \Illuminate\Http\Response
     */
    public function destroy(Companie $companie)
    {
        $companie->delete();
        return redirect()->route('companie.index')->with('status',__('Company successfully eliminated'));
    }
}

business_management/app/Http/Controllers/Admin/EmployeeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Employee;
use App\Companie;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\CreateEmployeeRequest;


class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin/record_employee',[
            'employees'=>Employee::first()->paginate(2)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin/employee',[
            'companies'=>Companie::get()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateEmployeeRequest $request)
    {
        Employee::create($request->validated());
        return redirect()->route('employee.create')->with('status',__('Successful registered employee'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        return view('admin/edit_employee',[
            'employee'=>$employee,
            'companies'=>Companie::get()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(CreateEmployeeRequest $request, Employee $employee)
    {
        $employee->update($request->validated());
        return redirect()->route('employee.index')->with('status',__('Updated Employee Successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();
        return redirect()->route('employee.index')->with('status',__('Employee removed successfully'));
    }
}

business_management/app/Http/Controllers/Admin/HomeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Companie;
use App\Employee;

class HomeController extends Controller
{
    public function index(){
        return view('admin/index',[
            'companies'=>Companie::count(),
            'employees'=>Employee::count()
        ]);
    }

}

business_management/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

business_management/resources/views/admin/companie.blade.php
@extends('adminlte::page')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                @include('partials/session-status')

                <div class="card mt-3">
                    <div class="card-header text-center">{{ __('Register Companie') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{route('companie.store')}}" enctype="multipart/form-data">
                            @csrf

                            <div class="form-group row">
                                <label for="logo" class="col-md-2 col-form-label text-md-right">{{ __('Logo') }}</label>

                                <div class="col-md-9">
                                    <input id="logo" type="file"  name="logo" value="{{ old('logo') }}" required autocomplete="logo">

                                    @error('logo')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="name" class="col-md-2 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-9">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email" class="col-md-2 col-form-label text-md-right">{{ __('Email') }}</label>

                                <div class="col-md-9">
                                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                                    @error('email')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="website" class="col-md-2 col-form-label text-md-right">{{ __('Website') }}</label>

                                <div class="col-md-9">
                                    <input id="website" type="text" class="form-control" name="website" value="{{ old('website') }}" required autocomplete="website">
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary w-100">
                                        {{ __('Register') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

business_management/resources/views/admin/edit_companie.blade.php
@extends('adminlte::page')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card mt-3">
                    <div class="card-header text-center">{{ __('Edit Companie') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{route('companie.update',$companie)}}" enctype="multipart/form-data">
                            @csrf @method('PUT')

                            <div class="form-group row">
                                <label for="logo" class="col-md-2 col-form-label text-md-right">{{ __('Logo') }}</label>

                                <div class="col-md-9">
                                    <input id="logo" type="file"  name="logo" autocomplete="logo">
                                    <a href="http://localhost:8000/storage/{{$companie->logo}}">{{$companie->name_logo}}</a>

                                    @error('logo')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="name" class="col-md-2 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-9">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name',$companie->name) }}" required autocomplete="name" autofocus>

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email" class="col-md-2 col-form-label text-md-right">{{ __('Email') }}</label>

                                <div class="col-md-9">
                                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email',$companie->email) }}" required autocomplete="email">

                                    @error('email')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="website" class="col-md-2 col-form-label text-md-right">{{ __('Website') }}</label>

                                <div class="col-md-9">
                                    <input id="website" type="text" class="form-control" name="website" value="{{ old('website',$companie->website) }}" required autocomplete="website">
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary w-100">
                                        {{ __('Edit') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

business_management/resources/views/admin/edit_employee.blade.php
@extends('adminlte::page')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card mt-3">
                    <div class="card-header text-center">{{ __('Edit Employee') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{route('employee.update',$employee)}}" enctype="multipart/form-data">
                            @csrf @method('PUT')

                            <div class="form-group row">
                                <label for="name" class="col-md-2 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-9">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name',$employee->name) }}" required autocomplete="name" autofocus>

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="surname" class="col-md-2 col-form-label text-md-right">{{ __('Surname') }}</label>

                                <div class="col-md-9">
                                    <input id="surname" type="text" class="form-control @error('surname') is-invalid @enderror" name="surname" value="{{ old('surname',$employee->surname) }}" required autocomplete="surname" autofocus>

                                    @error('surname')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email" class="col-md-2 col-form-label text-md-right">{{ __('Email') }}</label>

                                <div class="col-md-9">
                                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email',$employee->email) }}" required autocomplete="email">

                                    @error('email')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="phone" class="col-md-2 col-form-label text-md-right">{{ __('Phone') }}</label>

                                <div class="col-md-9">
                                    <input id="phone" type="text" class="form-control @error('phone') is-invalid @enderror" name="phone" value="{{ old('phone',$employee->phone) }}" required autocomplete="phone">

                                    @error('phone')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="companie_id" class="col-md-2 col-form-label text-md-right">{{ __('Companie') }}</label>

                                <div class="col-md-9">
                                    <select id="companie_id" class="form-select" name="companie_id" required>
                                        <option selected>select companie</option>
                                        @foreach($companies as $companie)
                                            @if($companie->id == $employee->companie_id)
                                                <option value="{{old('companie_id',$companie->id)}}" selected>{{$companie->name}}</option>
                                            @else
                                                <option value="{{old('companie_id',$companie->id)}}">{{$companie->name}}</option>
                                            @endif
                                        @endforeach
                                    </select>


                                    @error('companie_id')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary w-100">
                                        {{ __('Edit') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

business_management/resources/views/admin/employee.blade.php
@extends('adminlte::page')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                @include('partials/session-status')
                <div class="card mt-3">
                    <div class="card-header text-center">{{ __('Register Employee') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{route('employee.store')}}" enctype="multipart/form-data">
                            @csrf

                            <div class="form-group row">
                                <label for="name" class="col-md-2 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-9">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="surname" class="col-md-2 col-form-label text-md-right">{{ __('Surname') }}</label>

                                <div class="col-md-9">
                                    <input id="surname" type="text" class="form-control @error('surname') is-invalid @enderror" name="surname" value="{{ old('surname') }}" required autocomplete="surname" autofocus>

                                    @error('surname')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email" class="col-md-2 col-form-label text-md-right">{{ __('Email') }}</label>

                                <div class="col-md-9">
                                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                                    @error('email')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="phone" class="col-md-2 col-form-label text-md-right">{{ __('Phone') }}</label>

                                <div class="col-md-9">
                                    <input id="phone" type="text" class="form-control @error('phone') is-invalid @enderror" name="phone" value="{{ old('phone') }}" required autocomplete="phone">

                                    @error('phone')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="companie_id" class="col-md-2 col-form-label text-md-right">{{ __('Companie') }}</label>

                                <div class="col-md-9">
                                    <select id="companie_id" class="form-select" name="companie_id" required>
                                      <option selected>{{__('select companie')}}</option>
                                      @foreach($companies as $companie)
                                        <option value="{{$companie->id}}">{{$companie->name}}</option>
                                      @endforeach
                                    </select>


                                    @error('companie_id')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary w-100">
                                        {{ __('Register') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

business_management/resources/views/admin/record_companie.blade.php
@extends('adminlte::page')

@section('content')
    @include('partials/session-status')
	<div class="row">
		<div class="col mt-3">
			<table class="table table-sm">
			  	<thead class="thead-dark">
				    <tr>
				      	<th scope="col">{{__('id')}}</th>
				      	<th scope="col">{{__('name')}}</th>
				      	<th scope="col">{{__('email')}}</th>
				      	<th scope="col">{{__('logo')}}</th>
				      	<th scope="col">{{__('website')}}</th>
				      	<th scope="col">{{__('Edit')}}</th>
				      	<th scope="col">{{__('Delete')}}</th>
				    </tr>
			  	</thead>
			  	<tbody>
			  		@foreach($companies as $companie)
				  		<tr>
				      		<td>{{$companie->id}}</td>
				      		<td>{{$companie->name}}</td>
			      			<td>{{$companie->email}}</td>
				      		<td><img src="http://localhost:8000/storage/{{$companie->logo}}" alt=""  width="20" height="20"></td>
				      		<td>{{$companie->website}}</td>
				      		<td><a  class="btn btn-primary" role="button" href="{{route('companie.edit', $companie)}}">{{__('Edit')}}</a></td>
				      		<td>
				      			<form method="POST" action="{{route('companie.destroy',$companie)}}">
				      				@csrf @method('DELETE')
				      				<button class="btn btn-primary">{{__('Delete')}}</button>
				      			</form>
				      		</td>

				    	</tr>
			  		@endforeach
			  	</tbody>
			</table>
	  		{{$companies->links()}}
	  	</div>
  	</div>
@stop

business_management/resources/views/admin/record_employee.blade.php
@extends('adminlte::page')

@section('content')
	@include('partials/session-status')
	<div class="row">
		<div class="col mt-3">
			<table class="table table-sm">
			  	<thead class="thead-dark">
				    <tr>
				      	<th scope="col">{{__('id')}}</th>
				      	<th scope="col">{{__('name')}}</th>
				      	<th scope="col">{{__('surname')}}</th>
				      	<th scope="col">{{__('email')}}</th>
				      	<th scope="col">{{__('phone')}}</th>
				      	<th scope="col">{{__('companie_id')}}</th>
				      	<th scope="col">{{__('Edit')}}</th>
				      	<th scope="col">{{__('Delete')}}</th>
				    </tr>
			  	</thead>
			  	<tbody>
			  		@foreach($employees as $employee)
				    	<tr>
				      		<td>{{$employee->id}}</td>
			      			<td>{{$employee->name}}</td>
				      		<td>{{$employee->surname}}</td>
				      		<td>{{$employee->email}}</td>
				      		<td>{{$employee->phone}}</td>
				      		<td>{{$employee->companie_id}}</td>
				      		<td><a class="btn btn-primary" role="button"href="{{route('employee.edit',$employee)}}">{{__('Edit')}}</a></td>
				      		<td>
				      			<form method="POST" action="{{route('employee.destroy',$employee)}}">
				      				@csrf @method('DELETE')
				      				<button class="btn btn-primary">{{__('Delete')}}</button>
				      			</form>
				      		</td>
				    	</tr>
				    @endforeach
			  </tbody>
			</table>
			{{$employees->links()}}
		</div>
	</div>
@stop

business_management/resources/views/partials/session-status.blade.php
@if (session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
@endif